-- MySQL Script generated by MySQL Workbench
-- Fri Sep  1 13:44:04 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema NaomiStore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema NaomiStore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NaomiStore` DEFAULT CHARACTER SET latin1 ;
USE `NaomiStore` ;

-- -----------------------------------------------------
-- Table `NaomiStore`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NaomiStore`.`Account` (
  `accountId` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `password` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `name` VARCHAR(200) CHARACTER SET 'utf8' NOT NULL,
  `mail` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `role` INT(11) NOT NULL,
  PRIMARY KEY (`accountId`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `NaomiStore`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NaomiStore`.`Orders` (
  `orderId` INT(11) NOT NULL AUTO_INCREMENT,
  `createdDate` DATETIME NOT NULL,
  `orderTotal` FLOAT NOT NULL,
  `accountId` INT(11) NOT NULL,
  PRIMARY KEY (`orderId`, `accountId`),
  INDEX `fk_Orders_Account_idx` (`accountId` ASC),
  CONSTRAINT `fk_Orders_Account`
    FOREIGN KEY (`accountId`)
    REFERENCES `NaomiStore`.`Account` (`accountId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `NaomiStore`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NaomiStore`.`Product` (
  `productId` INT(11) NOT NULL AUTO_INCREMENT,
  `productName` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `productPrice` FLOAT NOT NULL,
  `productQuantity` INT(11) NOT NULL,
  PRIMARY KEY (`productId`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `NaomiStore`.`OrderItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NaomiStore`.`OrderItem` (
  `itemId` INT NOT NULL AUTO_INCREMENT,
  `itemTotal` FLOAT NOT NULL,
  `itemStatus` INT NOT NULL,
  `itemReason` NVARCHAR(100) NULL,
  `itemNote` NVARCHAR(100) NULL,
  `orderId` INT(11) NOT NULL,
  `productId` INT(11) NOT NULL,
  PRIMARY KEY (`itemId`, `orderId`, `productId`),
  INDEX `fk_OrderItem_Orders1_idx` (`orderId` ASC),
  INDEX `fk_OrderItem_Product1_idx` (`productId` ASC),
  CONSTRAINT `fk_OrderItem_Orders1`
    FOREIGN KEY (`orderId`)
    REFERENCES `NaomiStore`.`Orders` (`orderId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderItem_Product1`
    FOREIGN KEY (`productId`)
    REFERENCES `NaomiStore`.`Product` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
